### ISSUE TITLE
Possible error in UniswapV3Pool::simulate_swap

### ISSUE THREAD

**Issue by manelrovira** [darkforestry/amms-rs#96] opened 2023-08-30 05:03 UTC
Hi,
I'm simulating some swaps in a UniswapV3 pools and in some cases the simulation runs forever becuse the conditions to end the next while are never meet.

```
while current_state.amount_specified_remaining != I256::zero()
            && current_state.sqrt_price_x_96 != sqrt_price_limit_x_96
```

In other cases seems the simulation ends with an  Liquidity underflow Error when is enough liquidity in the pool.

Example: 
```
// WETH-LINK UniswapV3 pool
let pool = amm::uniswap_v3::UniswapV3Pool::new_from_address(
    "0xa6cc3c2531fdaa6ae1a3ca84c2855806728693e8".parse().unwrap(),
    0,
    provider.clone()
).await?;
   
// Simulate swap from WETH to LINK - CORRECT
let amount_out = pool.simulate_swap(
    "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2".parse().unwrap(),
    U256::from_dec_str("1000000000000000000")? // 1 WETH
)?;

println!("Amount out: {:?}", amount_out);

// Simulate swap from LINK to WETH - LIQUIDITY ERROR
let amount_out = pool.simulate_swap(
    "0x514910771af9ca656af840dff83e8264ecf986ca".parse().unwrap(),
    U256::from_dec_str("1000000000000000000000")? // 1000 LINK
)?;

println!("Amount out: {:?}", amount_out);
```

I'm trying to debug the simulate_swap function but i don't know the mechanincs of a v3 pool and it's a bit difficult for me but seems that the problem is fetching the next tick in the loop when zero_for_one is true.

I've added a print after the search of the next_tick:

```
//Get the next tick from the current tick
(step.tick_next, step.initialized) =
    uniswap_v3_math::tick_bitmap::next_initialized_tick_within_one_word(
        &self.tick_bitmap,
        current_state.tick,
        self.tick_spacing,
        zero_for_one,
)?;
          
println!("Current state tick = {} //  tick_next = {} ", current_state.tick, step.tick_next );    
```

And this are the results:

```
zero_for_one false
Current state tick = -56432 //  tick_next = -56340 
Amount out: 281430322851116089258
zero_for_one true
Current state tick = -56432 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Current state tick = -56401 //  tick_next = -56400 
Error: Liquidity underflow
```

**Comment by roman-raizen** [comment] 2023-09-10 07:55
Having same situation. Get's stuck on swap simulation 90% of the time. 

Wouldn't it make sense to change it to:
```
while current_state.amount_specified_remaining > I256::zero()
            && current_state.sqrt_price_x_96 != sqrt_price_limit_x_96
```
There could be a situation when we overshoot `amount_in` slightly (spending a bit more tokens as intended) and it would send us into an infinite loop.

**Comment by 0xOsiris** [comment] 2023-09-10 19:07
Hey guys thanks for making us aware of this. We are working on getting this issue resolved. We were able to reproduce the behavior in a test on `test/v3-sim`. Looks like the issue is a little more nuanced then we first expected (I think this breaks down to a bug in `uniswap_v3_math::next_initialized_tick_within_one_word` after writing some tests in the lib. Will have this patched ASAP

**Comment by manelrovira** [comment] 2023-09-10 19:44
Hi,
I think the problem is in the implementation of the simulate_swap function, more precisely in this if:

```
if current_state.sqrt_price_x_96 == step.sqrt_price_next_x96 {
    if step.initialized {
                 
        // STRIPED LINES

        //Increment the current tick
        current_state.tick = if zero_for_one {
            step.tick_next.wrapping_sub(1)
        } else {
            step.tick_next
        }
    }
}
```               
In the contract the update of the current_status tick is outside the **if** that checks if the current tick is initialized. Currently when you encounter an uninitialized tick you enter a loop because you never update the current_state tick.

Here you con find te uniswap contract (line 725).

https://github.com/Uniswap/v3-core/blob/d8b1c635c275d2a9450bd6a78f3fa2484fef73eb/contracts/UniswapV3Pool.sol#L693C1-L726C15

**Comment by manelrovira** [comment] 2023-09-10 19:47
Also maybe there is a problem with uniswap_v3_math::next_initialized_tick_within_one_word , i thinks is missing this piece that is present in the uniswap library.

```
  if tick < 0 && tick % tick_spacing != 0 {
        compressed -= 1;
    } 
```

**Comment by 0xOsiris** [comment] 2023-09-19 02:15
Closing per #97

**Closed by 0xOsiris** 2023-09-19 02:15 UTC
Labels: bug
