### ISSUE TITLE
Bug: Here the not correct way to launch examples(simulate-swap), if i use amms-rs in my own repo

### ISSUE THREAD

**Issue by Act0r1** [darkforestry/amms-rs#223] opened 2024-10-19 13:02 UTC
### Describe the bug

I just added my amms-rs to my own cargo.toml, here the my Cargo.toml:

```
[dependencies]
amms = "0.6.3"
alloy = {version= "0.4", features = ["full"]} # here i can replace with actual dev.dependecies that used in amms-rs, but error not going away
eyre = "0.6.12"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
tracing-subscriber = "0.3.18"

```

And i got there two errors: 

```
3. mismatched types
   `alloy::alloy_primitives::Address` and `Address` have similar names, but are actually distinct types
   perhaps two different versions of crate `alloy_primitives` are being used? [E0308]

```

and:

```
5. the trait bound `RootProvider<alloy::transports::alloy_transport_http::Http<Client>>: alloy_provider::provider::r#trait::Provider<_, _>` is not satisfied
   the following other types implement trait `alloy_provider::provider::r#trait::Provider<T, N>`:
     &'b U
     &'b mut U
     Arc<U>
     Box<U>
     Rc<U>
     alloy_provider::fillers::FillProvider<F, P, T, N>

```

here the way to fix it ?

**Comment by Act0r1** [comment] 2024-10-19 13:27
And if we check `new_from_address` func signature we see this:

 ```
   /// Creates a new instance of the pool from the pair address, and syncs the pool data.
    pub async fn new_from_address<T, N, P>(
        pair_address: Address,
        fee: u32,
        provider: Arc<P>,
    ) -> Result<Self, AMMError>

```

But in example there provided 4 args, expected 3

**Comment by Aviksaikat** [comment] 2024-10-28 08:33
I think it's a version problem. try with version `0.6.2`

**Comment by pstemporowski** [comment] 2024-11-01 18:42
The issue is that the released version on crates.io only supports Alloy v3 as a provider. 

To resolve this, you have a few options: 
you can downgrade your Alloy version to v3 or even try v2. 

Alternatively, you can use the GitHub version by adding `amms = {git = "https://github.com/darkforestry/amms-rs.git"}`, as Alloy dep was updated in #225

**Comment by 0xOsiris** [comment] 2024-11-03 20:16
Closing this.

Change your `Cargo.toml` to pin to alloy version 0.5, and add 

```
amms = { git = "https://github.com/darkforestry/amms-rs.git", rev = "791fac3" }
```

and things should compile.

**Closed by 0xOsiris** 2024-11-03 20:16 UTC
Labels: bug
